# Generated by Django 3.2.25 on 2025-04-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('servicios_escolares', '0003_auto_20250326_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('padre', 'Padre'), ('profesor', 'Profesor'), ('servicio_escolar', 'Servicio Escolar')], max_length=20)),
                ('usuario_id', models.PositiveIntegerField()),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En progreso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('url_pagina', models.URLField(blank=True, help_text='URL de la página donde ocurrió el problema (opcional)', max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Información del navegador del usuario', max_length=500, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='servicios_escolares.servicioescolar')),
                ('usuario_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
