# Generated by Django 3.2.25 on 2025-05-20 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios_escolares', '0003_auto_20250326_1002'),
        ('padres', '0005_padre_user'),
        ('estudiantes', '0013_estudiante_registro_token'),
        ('profesores', '0008_remove_clase_nivel_educativo_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Encuesta de Satisfacción', max_length=200)),
                ('descripcion', models.TextField(default='Por favor evalúa tu satisfacción con el sistema y las citas escolares')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_edicion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_creadas', to='servicios_escolares.servicioescolar')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
        migrations.CreateModel(
            name='EncuestaAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('aplicada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios_escolares.servicioescolar')),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.cicloescolar')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.encuesta')),
            ],
            options={
                'verbose_name': 'Encuesta Aplicada',
                'verbose_name_plural': 'Encuestas Aplicadas',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('escala_5', 'Escala del 1 al 5'), ('si_no', 'Sí/No'), ('texto', 'Respuesta abierta')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obligatoria', models.BooleanField(default=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='formularios.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('encuesta_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.encuestaaplicada')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padres.padre')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.pregunta')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
