# Generated by Django 3.2.25 on 2025-05-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='encuesta_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='formularios.encuesta'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='es_plantilla',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='encuestaaplicada',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='formularios.encuesta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='encuesta_aplicada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.encuestaaplicada'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.pregunta'),
        ),
    ]
