# Generated by Django 3.2.25 on 2025-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20250520_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='es_default',
            field=models.BooleanField(default=True, verbose_name='Es plantilla por defecto'),
        ),
    ]
