# Generated by Django 3.2.25 on 2025-05-21 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0004_auto_20250520_1347'),
        ('citas', '0011_auto_20250517_2344'),
        ('padres', '0006_auto_20250520_1347'),
        ('formularios', '0003_encuesta_es_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroalimentacionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Retroalimentación de Cita', max_length=200)),
                ('descripcion', models.TextField(default='Por favor comparte tu experiencia sobre la cita realizada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_edicion', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_plantilla', models.BooleanField(default=True)),
                ('es_default', models.BooleanField(default=True, verbose_name='Es plantilla por defecto')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones_creadas', to='servicios_escolares.servicioescolar')),
                ('retroalimentacion_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='formularios.retroalimentacioncita')),
            ],
            options={
                'verbose_name': 'Retroalimentación de Cita',
                'verbose_name_plural': 'Retroalimentaciones de Citas',
            },
        ),
        migrations.CreateModel(
            name='RetroalimentacionAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('completada', models.BooleanField(default=False)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentacion', to='citas.cita')),
                ('retroalimentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='formularios.retroalimentacioncita')),
            ],
            options={
                'verbose_name': 'Retroalimentación Aplicada',
                'verbose_name_plural': 'Retroalimentaciones Aplicadas',
            },
        ),
        migrations.CreateModel(
            name='PreguntaRetroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('escala_5', 'Escala del 1 al 5'), ('si_no', 'Sí/No'), ('si_no_explicacion', 'Sí/No con explicación'), ('texto', 'Respuesta abierta')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obligatoria', models.BooleanField(default=True)),
                ('permite_explicacion', models.BooleanField(default=False, help_text='Si es Sí/No, ¿permite explicación adicional?')),
                ('retroalimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='formularios.retroalimentacioncita')),
            ],
            options={
                'verbose_name': 'Pregunta de Retroalimentación',
                'verbose_name_plural': 'Preguntas de Retroalimentación',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaRetroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numero', models.IntegerField(blank=True, help_text='Valor numérico para preguntas de escala', null=True)),
                ('respuesta_si_no', models.BooleanField(blank=True, help_text='Respuesta Sí/No', null=True)),
                ('explicacion', models.TextField(blank=True, help_text='Explicación adicional para respuestas Sí/No', null=True)),
                ('respuesta_texto', models.TextField(blank=True, help_text='Respuesta de texto libre', null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_retroalimentacion', to='padres.padre')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.preguntaretroalimentacion')),
                ('retroalimentacion_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.retroalimentacionaplicada')),
            ],
            options={
                'verbose_name': 'Respuesta de Retroalimentación',
                'verbose_name_plural': 'Respuestas de Retroalimentación',
                'unique_together': {('retroalimentacion_aplicada', 'pregunta', 'padre')},
            },
        ),
    ]
