# Generated by Django 3.2.25 on 2025-05-21 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0006_auto_20250520_1347'),
        ('citas', '0011_auto_20250517_2344'),
        ('formularios', '0004_preguntaretroalimentacion_respuestaretroalimentacion_retroalimentacionaplicada_retroalimentacioncita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestaretroalimentacion',
            options={'ordering': ['pregunta__orden'], 'verbose_name': 'Respuesta de Retroalimentación', 'verbose_name_plural': 'Respuestas de Retroalimentación'},
        ),
        migrations.AlterModelOptions(
            name='retroalimentacionaplicada',
            options={'ordering': ['-fecha_aplicacion'], 'verbose_name': 'Retroalimentación Aplicada', 'verbose_name_plural': 'Retroalimentaciones Aplicadas'},
        ),
        migrations.AddField(
            model_name='retroalimentacionaplicada',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AlterField(
            model_name='respuestaretroalimentacion',
            name='padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_retroalimentacion', to='padres.padre', verbose_name='Padre que respondió'),
        ),
        migrations.AlterField(
            model_name='respuestaretroalimentacion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.preguntaretroalimentacion', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='respuestaretroalimentacion',
            name='retroalimentacion_aplicada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formularios.retroalimentacionaplicada', verbose_name='Retroalimentación aplicada'),
        ),
        migrations.AlterField(
            model_name='retroalimentacionaplicada',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentacion', to='citas.cita', verbose_name='Cita asociada'),
        ),
        migrations.AlterField(
            model_name='retroalimentacionaplicada',
            name='completada',
            field=models.BooleanField(default=False, verbose_name='¿Completada?'),
        ),
        migrations.AlterField(
            model_name='retroalimentacionaplicada',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='retroalimentacionaplicada',
            name='retroalimentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='formularios.retroalimentacioncita', verbose_name='Plantilla de retroalimentación'),
        ),
    ]
