# Generated by Django 3.2.25 on 2025-05-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_auto_20250521_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaretroalimentacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='preguntaretroalimentacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='preguntaretroalimentacion',
            name='pregunta_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nuevas_versiones', to='formularios.preguntaretroalimentacion', verbose_name='Pregunta original'),
        ),
    ]
