# Generated by Django 3.2.25 on 2025-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_auto_20250523_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaretroalimentacion',
            name='activa',
            field=models.BooleanField(default=True, help_text='¿Esta pregunta está activa en el formulario?'),
        ),
    ]
