# Generated by Django 3.2.25 on 2025-05-24 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_alter_respuestaretroalimentacion_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaretroalimentacion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='formularios.preguntaretroalimentacion', verbose_name='Pregunta'),
        ),
    ]
