# Generated by Django 3.2.25 on 2025-05-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_alter_respuestaretroalimentacion_pregunta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='encuesta',
            constraint=models.UniqueConstraint(condition=models.Q(('es_default', True)), fields=('creada_por', 'es_default'), name='unique_default_per_servicio'),
        ),
    ]
