# Generated by Django 3.2.25 on 2025-05-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0009_auto_20250520_1347'),
        ('formularios', '0011_encuesta_unique_default_per_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroalimentacionaplicada',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retroalimentaciones_recibidas', to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='retroalimentacioncita',
            name='es_para_profesor',
            field=models.BooleanField(default=False, verbose_name='¿Es para citas con profesores?'),
        ),
    ]
