"""
Django settings for MACE project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

from django.contrib import staticfiles

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Configuración para desarrollo local
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
DEBUG = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h$@lq%w6dl(ss4d8_+q&4kvzez3v##^=t#-3etu3+vl-6%*&20'

# SECURITY WARNING: don't run with debug turned on in production!

# Permitir iframes desde el mismo origen (para la demo)
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Cambia de 'DENY' a 'SAMEORIGIN'

# También necesitas esto para iframes:
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pwa',
    'padres',
    'profesores',
    'servicios_escolares',
    'citas',
    'calendario',
    'notificaciones',
    'estudiantes',
    'crispy_forms',
    'crispy_bootstrap5',  # Añade esto
    'django.contrib.humanize',
    'ticket_soporte',
    'preguntas',
    'nota',
    'formularios',
    'widget_tweaks',
    'MACE',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'servicios_escolares.middleware.NotificacionesMiddleware',
    'profesores.middleware.ProfesorNotificacionesMiddleware',  # Ajusta el path según donde pongas este middleware
    'padres.middleware.PadreNotificacionesMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

# Configuración CORS (para desarrollo)
CORS_ALLOW_ALL_ORIGINS = True  # Solo para desarrollo!
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'MACE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # ... otros context processors de Django ...
                'profesores.context_processors.notificaciones_profesor',
                'padres.context_processors.notificaciones_padre',
                'servicios_escolares.context_processors.theme_context',
                'profesores.context_processors.profesor_context',
                'padres.context_processors.padre_context',
                'servicios_escolares.context_processors.eventos_servicio_escolar',
                'preguntas.context_processors.faq_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'MACE.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Asegúrate de tener esto en tus settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'serviciosescolares_session'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = True
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Durante desarrollo (DEBUG=True)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# MEDIA_URL = '/media/'  # No debe terminar en /
# MEDIA_ROOT = r'C:\Users\denis\Pictures\MACE\media'  # Ruta absoluta con r
# DEBUG = True  # Debe ser True para desarrollo

# Para producción (DEBUG=False)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Nombre de tu sitio (útil para los emails)
SITE_NAME = 'MACE'  # Cambia esto por el nombre de tu sistema
# Configuración de tiempo de expiración de invitación (opcional)
INVITATION_EXPIRE_DAYS = 7

# Configuración de email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Para producción
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Para desarrollo (imprime en consola)

DEFAULT_FROM_EMAIL = 'emilio142018@gmail.com'  # Cambia esto por tu email, no-reply@tudominio.com
SERVER_EMAIL = 'emilio142018@gmail.com'  # Email para errores del servidor

# Configuración SMTP (ejemplo para Gmail)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tucorreo@gmail.com'  # Cambiar por tu email
EMAIL_HOST_PASSWORD = 'emilenial067'  # Cambiar por tu contraseña o app password
