# Generated by Django 3.2.25 on 2025-04-30 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios_escolares', '0003_auto_20250326_1002'),
        ('profesores', '0006_tiempolibreprofesor'),
        ('padres', '0004_auto_20250329_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('academica', 'Académica'), ('conducta', 'Conducta'), ('administrativa', 'Administrativa')], default='general', max_length=20, verbose_name='Tipo de nota')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='notas/imagenes/', verbose_name='Imagen adjunta')),
                ('documento', models.FileField(blank=True, null=True, upload_to='notas/documentos/', verbose_name='Documento adjunto')),
                ('audio', models.FileField(blank=True, null=True, upload_to='notas/audios/', verbose_name='Audio adjunto')),
                ('creador_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas_padre', to='padres.padre')),
                ('creador_profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas_profesor', to='profesores.profesor')),
                ('creador_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas_servicio', to='servicios_escolares.servicioescolar')),
                ('destinatario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recibidas_padre', to='padres.padre')),
                ('destinatario_profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recibidas_profesor', to='profesores.profesor')),
                ('destinatario_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recibidas_servicio', to='servicios_escolares.servicioescolar')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
