# Generated by Django 3.2.25 on 2025-04-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField(help_text='Usa {variable} para marcadores de posición')),
                ('destinatarios', models.CharField(choices=[('padre', 'Padres'), ('profesor', 'Profesores'), ('servicio', 'Servicio Escolar'), ('todos', 'Todos los usuarios')], default='todos', max_length=20)),
                ('tipo_evento', models.CharField(choices=[('cita', 'Citas'), ('feedback', 'Feedback'), ('academico', 'Académico'), ('soporte', 'Soporte'), ('general', 'General'), ('custom', 'Personalizado')], default='general', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creador_id', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creador_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('nombre', 'destinatarios', 'tipo_evento')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('padre_cita_creada', 'Nueva cita programada'), ('padre_cita_modificada', 'Cambio en tu cita'), ('padre_cita_cancelada', 'Cita cancelada'), ('padre_feedback_pendiente', 'Feedback pendiente'), ('padre_feedback_recibido', 'Respuesta a tu feedback'), ('padre_calificacion', 'Nueva calificación'), ('padre_incidencia', 'Incidencia académica'), ('profesor_cita_creada', 'Tienes una nueva cita'), ('profesor_cita_modificada', 'Cambio en tu cita'), ('profesor_cita_cancelada', 'Cita cancelada'), ('profesor_feedback_pendiente', 'Feedback pendiente'), ('profesor_cita_proxima', 'Recordatorio de cita'), ('profesor_incidencia', 'Incidencia reportada'), ('servicio_nuevo_padre', 'Nuevo padre registrado'), ('registro_padre', 'Nuevo padre registrado'), ('servicio_ticket', 'Nuevo ticket de soporte'), ('servicio_incidencia', 'Incidencia académica'), ('servicio_recordatorio', 'Recordatorio importante'), ('recordatorio_general', 'Recordatorio importante'), ('custom', 'Notificación personalizada')], default='custom', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rol_destinatario', models.CharField(choices=[('padre', 'Padre'), ('profesor', 'Profesor'), ('servicio', 'Servicio Escolar'), ('todos', 'Todos los usuarios')], default='todos', max_length=20)),
                ('variable_1', models.CharField(blank=True, max_length=100, null=True)),
                ('variable_2', models.CharField(blank=True, max_length=100, null=True)),
                ('variable_3', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='contenttypes.contenttype')),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_relacionadas', to='contenttypes.contenttype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to='notificaciones.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('create_custom_notification', 'Puede crear notificaciones personalizadas'), ('use_advanced_templates', 'Puede utilizar plantillas avanzadas')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_ct', 'recipient_id'], name='notificacio_recipie_ffb712_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type'], name='notificacio_event_t_e2f9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificacio_is_read_e107b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['template'], name='notificacio_templat_961cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['rol_destinatario'], name='notificacio_rol_des_27ad83_idx'),
        ),
    ]
