# Generated by Django 3.2.25 on 2025-04-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('padre_cita_creada', 'Nueva cita programada'), ('padre_cita_modificada', 'Cambio en tu cita'), ('padre_cita_cancelada', 'Cita cancelada'), ('padre_feedback_pendiente', 'Feedback pendiente'), ('padre_feedback_recibido', 'Respuesta a tu feedback'), ('padre_calificacion', 'Nueva calificación'), ('padre_incidencia', 'Incidencia académica'), ('profesor_cita_creada', 'Tienes una nueva cita'), ('profesor_cita_modificada', 'Cambio en tu cita'), ('profesor_cita_cancelada', 'Cita cancelada'), ('profesor_feedback_pendiente', 'Feedback pendiente'), ('profesor_cita_proxima', 'Recordatorio de cita'), ('profesor_incidencia', 'Incidencia reportada'), ('registro_padre', 'Nuevo padre registrado'), ('servicio_nuevo_profesor', 'Nuevo profesor registrado'), ('recordatorio_general', 'Recordatorio importante'), ('custom', 'Notificación personalizada'), ('servicio_ticket', 'Nuevo ticket de soporte'), ('servicio_ticket_asignado', 'Ticket asignado')], default='custom', max_length=50),
        ),
    ]
