# Generated by Django 3.2.25 on 2025-04-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificaciones', '0004_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificacio_templat_961cd6_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='template',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='variable_1',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='variable_2',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='variable_3',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('padre_cita_creada', 'Nueva cita programada'), ('padre_cita_modificada', 'Cambio en tu cita'), ('padre_cita_cancelada', 'Cita cancelada'), ('padre_feedback_pendiente', 'Feedback pendiente'), ('padre_feedback_recibido', 'Respuesta a tu feedback'), ('padre_calificacion', 'Nueva calificación'), ('padre_incidencia', 'Incidencia académica'), ('profesor_cita_creada', 'Tienes una nueva cita'), ('profesor_cita_modificada', 'Cambio en tu cita'), ('profesor_cita_cancelada', 'Cita cancelada'), ('profesor_feedback_pendiente', 'Feedback pendiente'), ('profesor_cita_proxima', 'Recordatorio de cita'), ('profesor_incidencia', 'Incidencia reportada'), ('registro_padre', 'Nuevo padre registrado'), ('servicio_nuevo_profesor', 'Nuevo profesor registrado'), ('servicio_ticket', 'Nuevo ticket de soporte'), ('servicio_ticket_asignado', 'Ticket asignado'), ('recordatorio_general', 'Recordatorio importante'), ('custom', 'Notificación personalizada')], default='custom', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender_ct', 'sender_id'], name='notificacio_sender__4356a8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificacio_created_bdfda0_idx'),
        ),
    ]
