# Generated by Django 3.2.25 on 2025-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, unique=True)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('telefono_respaldo', models.CharField(blank=True, max_length=20, null=True)),
                ('rol_usuario', models.CharField(default='Servicio Escolar', max_length=50)),
                ('estado_cuenta', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('ultima_fecha_sesion', models.DateField(blank=True, null=True)),
                ('imagen_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('datos_personales', models.TextField(blank=True, null=True)),
                ('horario_atencion', models.TextField(blank=True, null=True)),
                ('estado_disponibilidad', models.CharField(max_length=50)),
            ],
        ),
    ]
