# Generated by Django 3.2.25 on 2025-03-26 08:47

from django.db import migrations, models
import servicios_escolares.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioescolar',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicioescolar',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicioescolar',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='servicioescolar',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='servicioescolar',
            name='estado_cuenta',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicioescolar',
            name='estado_disponibilidad',
            field=models.CharField(default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicioescolar',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicioescolar',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=servicios_escolares.models.user_image_path, verbose_name='Imagen de perfil'),
        ),
    ]
