# Generated by Django 3.2.25 on 2025-03-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0002_auto_20250326_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioescolar',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='servicioescolar',
            name='token_expiration',
        ),
    ]
