# Generated by Django 3.2.25 on 2025-05-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0004_auto_20250520_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_theme', models.CharField(choices=[('css/themes/tema1.css', 'Tema Azul'), ('css/themes/tema2.css', 'Tema Oscuro'), ('css/themes/tema3.css', 'Tema Claro')], default='css/themes/tema1.css', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios_escolares.servicioescolar')),
            ],
            options={
                'verbose_name': 'Configuración de Tema',
            },
        ),
    ]
