# Generated by Django 3.2.25 on 2025-05-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0005_themeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfig',
            name='active_theme',
            field=models.CharField(choices=[('css/themes/default.css', 'Tema Default'), ('css/themes/dark.css', 'Tema Oscuro'), ('css/themes/light.css', 'Tema Claro')], default='css/themes/default.css', max_length=100),
        ),
    ]
