# Generated by Django 3.2.25 on 2025-05-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0006_alter_themeconfig_active_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfig',
            name='active_theme',
            field=models.CharField(choices=[('css/%20themes/default.css', 'Tema Default'), ('css/%20themes/dark.css', 'Tema Oscuro'), ('css/%20themes/light.css', 'Tema Claro')], default='css/themes/default.css', max_length=100),
        ),
    ]
