# Generated by Django 3.2.25 on 2025-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0007_alter_themeconfig_active_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeconfig',
            name='active_theme',
        ),
        migrations.RemoveField(
            model_name='themeconfig',
            name='last_updated_by',
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='allow_padres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='allow_profesors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='global_theme',
            field=models.CharField(choices=[('css/themes/default.css', 'Tema Default'), ('css/themes/dark.css', 'Tema Oscuro'), ('css/themes/light.css', 'Tema Claro')], default='css/themes/default.css', max_length=100),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='last_updated_by_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='last_updated_by_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
