# Generated by Django 3.2.25 on 2025-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0008_auto_20250527_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfig',
            name='global_theme',
            field=models.CharField(choices=[('css/%20themes/default.css', 'Tema Default'), ('css/%20themes/dark.css', 'Tema Oscuro'), ('css/%20themes/light.css', 'Tema Claro')], default='css/%20themes/default.css', max_length=100),
        ),
    ]
