# Generated by Django 3.2.25 on 2025-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_escolares', '0009_alter_themeconfig_global_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfig',
            name='global_theme',
            field=models.CharField(choices=[('css/themes/default.css', 'Tema Default'), ('css/themes/dark.css', 'Tema Oscuro'), ('css/themes/light.css', 'Tema Claro')], default='css/themes/default.css', max_length=100),
        ),
    ]
