# Generated by Django 3.2.25 on 2025-04-28 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Servicio Escolar', 'Servicio Escolar'), ('Profesor', 'Profesor'), ('Padre', 'Padre'), ('General', 'General')], default='General', max_length=50)),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta y Respuesta',
                'verbose_name_plural': 'Preguntas y Respuestas',
                'ordering': ['rol', 'pregunta'],
                'unique_together': {('rol', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='HistorialAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_usuario', models.CharField(max_length=50)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fue_util', models.BooleanField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_ayuda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Ayuda',
                'verbose_name_plural': 'Historiales de Ayuda',
                'ordering': ['-fecha'],
            },
        ),
    ]
