# Generated by Django 3.2.25 on 2025-04-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntarespuesta',
            name='rol',
            field=models.CharField(choices=[('padre', 'Padre'), ('profesor', 'Profesor'), ('servicio', 'Servicio Escolar'), ('general', 'General')], max_length=20),
        ),
    ]
