# Generated by Django 3.2.25 on 2025-12-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_alter_preguntarespuesta_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntarespuesta',
            options={'ordering': ['rol', 'orden', 'pregunta'], 'verbose_name': 'Pregunta y Respuesta', 'verbose_name_plural': 'Preguntas y Respuestas'},
        ),
        migrations.AddField(
            model_name='preguntarespuesta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preguntarespuesta',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
