# Generated by Django 3.2.25 on 2025-03-29 03:20

import citas.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0003_auto_20250328_2120'),
        ('profesores', '0004_alter_profesor_imagen_usuario'),
        ('servicios_escolares', '0003_auto_20250326_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Reunión', max_length=100)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('orientacion', 'Orientación'), ('emergencia', 'Emergencia')], max_length=50)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('duracion', models.PositiveIntegerField(default=30, help_text='Duración en minutos', validators=[django.core.validators.MinValueValidator(15)])),
                ('fecha_hora_fin', models.DateTimeField(editable=False)),
                ('ubicacion', models.CharField(default='Escuela', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=50)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evento_google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('evento_microsoft_id', models.CharField(blank=True, max_length=255, null=True)),
                ('evento_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.profesor')),
                ('servicio_escolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios_escolares.servicioescolar')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_solicitadas', to='padres.padre')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=citas.models.evidencia_upload_path)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('otro', 'Otro')], default='documento', max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Evidencia de Cita',
                'verbose_name_plural': 'Evidencias de Citas',
            },
        ),
    ]
