# Generated by Django 3.2.25 on 2025-03-31 19:01

import citas.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0004_alter_profesor_imagen_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios_escolares', '0003_auto_20250326_1002'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha_hora_inicio'], 'permissions': [('cancelar_cita', 'Puede cancelar cualquier cita'), ('reprogramar_cita', 'Puede reprogramar citas')], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='evidenciacita',
            options={'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencias'},
        ),
        migrations.RemoveField(
            model_name='evidenciacita',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cita',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciacita',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos (mínimo 15)', validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', '\U0001f7e1 Pendiente'), ('confirmada', '\U0001f7e2 Confirmada'), ('completada', '🔵 Completada'), ('cancelada', '🔴 Cancelada'), ('reprogramada', '\U0001f7e0 Reprogramada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='evento_google_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Evento Google Calendar'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='evento_microsoft_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Evento Outlook'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='evento_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace al Evento'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_inicio',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now, message='No se pueden agendar citas en el pasado')]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(help_text='Describa el propósito de la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='profesores.profesor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agendadas', to='servicios_escolares.servicioescolar'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('academica', '📚 Académica'), ('administrativa', '📋 Administrativa'), ('orientacion', '\U0001f9ed Orientación'), ('emergencia', '🚨 Emergencia'), ('otra', '❔ Otra')], default='academica', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='titulo',
            field=models.CharField(default='Reunión', help_text='Ej: Reunión sobre rendimiento académico', max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='ubicacion',
            field=models.CharField(blank=True, default='Escuela', max_length=100),
        ),
        migrations.AlterField(
            model_name='evidenciacita',
            name='archivo',
            field=models.FileField(upload_to=citas.models.evidencia_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'docx', 'xlsx'])]),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora_inicio'], name='citas_cita_fecha_h_296f64_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['solicitante', 'profesor'], name='citas_cita_solicit_9e633c_idx'),
        ),
    ]
