# Generated by Django 3.2.25 on 2025-04-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20250331_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'permissions': [('ver_calendario_propio', 'Puede ver su propio calendario de citas'), ('ver_calendario_general', 'Puede ver el calendario general de citas')]},
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_cita_fecha_h_296f64_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_cita_estado_2000d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_cita_solicit_9e633c_idx',
        ),
    ]
