# Generated by Django 3.2.25 on 2025-04-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0004_auto_20250329_0211'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('servicios_escolares', '0003_auto_20250326_1002'),
        ('profesores', '0006_tiempolibreprofesor'),
        ('citas', '0003_auto_20250405_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='cita',
            name='asistentes_padres',
            field=models.ManyToManyField(blank=True, related_name='citas_como_asistente', to='padres.Padre'),
        ),
        migrations.AddField(
            model_name='cita',
            name='asistentes_profesores',
            field=models.ManyToManyField(blank=True, related_name='citas_como_asistente', to='profesores.Profesor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='asistentes_servicio',
            field=models.ManyToManyField(blank=True, related_name='citas_como_asistente', to='servicios_escolares.ServicioEscolar'),
        ),
        migrations.AddField(
            model_name='cita',
            name='creador_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='creador_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
