# Generated by Django 3.2.25 on 2025-05-07 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('citas', '0004_auto_20250429_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificacionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_object_id', models.PositiveIntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('motivo', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='citas.cita')),
                ('creator_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
