# Generated by Django 3.2.25 on 2025-05-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_estudiante_registro_token'),
        ('citas', '0005_modificacioncita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estudiantes',
            field=models.ManyToManyField(related_name='citas', to='estudiantes.Estudiante', verbose_name='Estudiantes involucrados'),
        ),
    ]
