# Generated by Django 3.2.25 on 2025-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_estudiantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha_hora_inicio'], 'permissions': [('cancelar_cita', 'Puede cancelar cualquier cita'), ('reprogramar_cita', 'Puede reprogramar citas'), ('ver_calendario_propio', 'Puede ver su propio calendario de citas'), ('ver_calendario_general', 'Puede ver el calendario general de citas')], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos (mínimo 15)'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora_inicio'], name='citas_cita_fecha_h_296f64_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['solicitante', 'profesor'], name='citas_cita_solicit_9e633c_idx'),
        ),
    ]
