# Generated by Django 3.2.25 on 2025-05-14 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0008_remove_clase_nivel_educativo_char'),
        ('servicios_escolares', '0003_auto_20250326_1002'),
        ('padres', '0005_padre_user'),
        ('citas', '0007_auto_20250511_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciacita',
            name='subido_por',
        ),
        migrations.AddField(
            model_name='evidenciacita',
            name='subido_por_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='padres.padre'),
        ),
        migrations.AddField(
            model_name='evidenciacita',
            name='subido_por_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.profesor'),
        ),
        migrations.AddField(
            model_name='evidenciacita',
            name='subido_por_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios_escolares.servicioescolar'),
        ),
        migrations.CreateModel(
            name='CitaPrioritaria',
            fields=[
                ('cita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='citas.cita')),
                ('nivel_prioridad', models.CharField(choices=[('critica', '🔴 Crítica (Requiere acción inmediata)'), ('alta', '\U0001f7e0 Alta (Urgente - Resolver en 24h)'), ('media', '\U0001f7e1 Media (Importante - Resolver en 72h)')], default='alta', max_length=20)),
                ('tipo_urgencia', models.CharField(choices=[('disciplinaria', '⚖️ Situación disciplinaria'), ('academica', '📚 Crisis académica'), ('salud', '🏥 Emergencia de salud'), ('seguridad', '🚨 Incidente de seguridad'), ('otra', '❗ Otra urgencia')], default='disciplinaria', max_length=20)),
                ('escalado_autoridades', models.BooleanField(default=False, help_text='¿Requiere intervención de autoridades superiores?')),
                ('tiempo_max_resolucion', models.PositiveIntegerField(default=24, help_text='Horas máximas para resolver (1-72h)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)])),
                ('autoridades_notificadas', models.ManyToManyField(blank=True, related_name='citas_prioritarias_notificadas', to='profesores.Profesor')),
            ],
            options={
                'verbose_name': 'Cita Prioritaria',
                'verbose_name_plural': 'Citas Prioritarias',
                'ordering': ['nivel_prioridad', 'fecha_hora_inicio'],
                'permissions': [('escalar_prioridad', 'Puede escalar citas a prioridad crítica'), ('ver_todas_prioritarias', 'Puede ver todas las citas prioritarias')],
            },
            bases=('citas.cita',),
        ),
    ]
