# Generated by Django 3.2.25 on 2025-05-14 18:05

import citas.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_auto_20250514_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaprioritaria',
            name='evidencia_archivo',
            field=models.FileField(blank=True, help_text='Archivo de evidencia adjunto (opcional)', null=True, upload_to=citas.models.evidencia_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'docx', 'xlsx'])]),
        ),
    ]
