# Generated by Django 3.2.25 on 2025-05-17 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('citas', '0009_citaprioritaria_evidencia_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaprioritaria',
            name='autor_prioridad',
            field=models.CharField(blank=True, help_text='Quién marcó la prioridad', max_length=100),
        ),
        migrations.AddField(
            model_name='citaprioritaria',
            name='fecha_marcado_prioridad',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se marcó la prioridad', null=True),
        ),
        migrations.AddField(
            model_name='citaprioritaria',
            name='motivo_prioridad',
            field=models.TextField(blank=True, help_text='Explicación detallada de la prioridad asignada', null=True),
        ),
        migrations.AlterField(
            model_name='citaprioritaria',
            name='evidencia_archivo',
            field=models.FileField(blank=True, help_text='Archivo de evidencia adjunto (opcional)', null=True, upload_to='evidencias_citas/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'docx', 'xlsx'])]),
        ),
        migrations.CreateModel(
            name='ReprogramacionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_original', models.DateTimeField()),
                ('fecha_hora_nueva', models.DateTimeField()),
                ('motivo', models.TextField(help_text='Motivo de la reprogramación')),
                ('realizado_por_id', models.PositiveIntegerField(null=True)),
                ('fecha_reprogramacion', models.DateTimeField(auto_now_add=True)),
                ('titulo_original', models.CharField(blank=True, max_length=100)),
                ('tipo_original', models.CharField(blank=True, max_length=50)),
                ('duracion_original', models.PositiveIntegerField(null=True)),
                ('ubicacion_original', models.CharField(blank=True, max_length=100)),
                ('motivo_original', models.TextField(blank=True)),
                ('estado_original', models.CharField(blank=True, max_length=50)),
                ('cita_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones', to='citas.cita')),
                ('realizado_por_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Reprogramación de Cita',
                'verbose_name_plural': 'Reprogramaciones de Citas',
                'ordering': ['-fecha_reprogramacion'],
            },
        ),
    ]
