# Generated by Django 3.2.25 on 2025-05-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_auto_20250517_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citaprioritaria',
            name='escalado_autoridades',
        ),
        migrations.RemoveField(
            model_name='citaprioritaria',
            name='tiempo_max_resolucion',
        ),
        migrations.RemoveField(
            model_name='citaprioritaria',
            name='tipo_urgencia',
        ),
    ]
