# Generated by Django 3.2.25 on 2025-04-01 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Formato: AAAA-AAAA (ej: 2023-2024)', max_length=9, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('actual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ciclo Escolar',
                'verbose_name_plural': 'Ciclos Escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('nombre', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['nivel__orden', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('C', 'Completo')], default='M', max_length=1)),
                ('capacidad', models.PositiveSmallIntegerField(default=30)),
                ('aula', models.CharField(blank=True, max_length=10)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='estudiantes.grado')),
            ],
            options={
                'ordering': ['grado__nivel__orden', 'grado__numero', 'letra'],
                'unique_together': {('grado', 'ciclo', 'letra', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria'), ('BAC', 'Bachillerato'), ('LIC', 'Licenciatura')], default='PRI', max_length=3, unique=True)),
                ('nombre', models.CharField(editable=False, max_length=50)),
                ('orden', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('SEM', 'Semestral'), ('TRI', 'Trimestral'), ('CUA', 'Cuatrimestral'), ('ANL', 'Anual')], default='ANL', max_length=3, unique=True)),
                ('nombre', models.CharField(editable=False, max_length=20)),
                ('meses_duracion', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Periodo Escolar',
                'verbose_name_plural': 'Periodos Escolares',
            },
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='estudiantes.niveleducativo'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CURP inválida.', regex='^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z]{2}$')])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('grupo_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.grupo')),
            ],
            options={
                'ordering': ['grupo_actual', 'apellido_paterno', 'apellido_materno'],
            },
        ),
        migrations.AddField(
            model_name='cicloescolar',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.niveleducativo'),
        ),
        migrations.AddField(
            model_name='cicloescolar',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.periodoescolar'),
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='estudiantes.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='estudiantes.grupo')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
                'unique_together': {('estudiante', 'grupo', 'fecha_ingreso')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grado',
            unique_together={('nivel', 'numero')},
        ),
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.UniqueConstraint(condition=models.Q(('actual', True)), fields=('actual',), name='unique_ciclo_actual'),
        ),
    ]
