# Generated by Django 3.2.25 on 2025-04-01 07:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['nivel__orden', 'numero'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['grado__nivel__orden', 'grado__numero', 'letra'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.RemoveField(
            model_name='cicloescolar',
            name='nivel',
        ),
        migrations.AddField(
            model_name='cicloescolar',
            name='meses_duracion',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Duración en meses'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='¿Ciclo activo?'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='actual',
            field=models.BooleanField(default=False, help_text='Ciclo que se está trabajando actualmente', verbose_name='¿Ciclo actual?'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='nombre',
            field=models.CharField(help_text='Formato: AAAA-AAAA (ej: 2023-2024)', max_length=9, unique=True, verbose_name='Nombre del ciclo'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.periodoescolar', verbose_name='Periodo escolar asociado'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ej: Primer grado, Segundo año', max_length=30),
        ),
        migrations.AlterField(
            model_name='grado',
            name='numero',
            field=models.PositiveSmallIntegerField(help_text='Número del grado (1 a 12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='aula',
            field=models.CharField(blank=True, help_text='Número o identificador del aula', max_length=10),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='capacidad',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='letra',
            field=models.CharField(help_text='Letra identificadora (A, B, C...)', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.UniqueConstraint(fields=('fecha_inicio', 'fecha_fin'), name='unique_fechas_ciclo'),
        ),
    ]
