# Generated by Django 3.2.25 on 2025-04-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_auto_20250401_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloescolar',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estudiantes.niveleducativo', verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='codigo',
            field=models.CharField(choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria'), ('BAC', 'Bachillerato'), ('LIC', 'Licenciatura')], default='SEC', max_length=3, unique=True),
        ),
    ]
