# Generated by Django 3.2.25 on 2025-04-01 21:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_auto_20250401_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['grupo_actual', 'apellido_paterno', 'apellido_materno'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='periodoescolar',
            options={},
        ),
        migrations.RemoveField(
            model_name='cicloescolar',
            name='periodo',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ciclo_inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.cicloescolar', verbose_name='Ciclo de Inscripción'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.niveleducativo', verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estatus Activo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_paterno',
            field=models.CharField(max_length=50, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curp',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CURP inválida.', regex='^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z]{2}$')], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.grupo', verbose_name='Grupo Actual'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='codigo',
            field=models.CharField(choices=[('SEM', 'Semestral'), ('TRI', 'Trimestral'), ('CUA', 'Cuatrimestral'), ('ANL', 'Anual')], max_length=3, unique=True),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['apellido_paterno', 'apellido_materno'], name='estudiantes_apellid_ba869b_idx'),
        ),
    ]
