# Generated by Django 3.2.25 on 2025-04-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_auto_20250401_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grados_del_ciclo', to='estudiantes.cicloescolar', verbose_name='Ciclo Escolar'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_por_nivel', to='estudiantes.niveleducativo'),
        ),
        migrations.AlterUniqueTogether(
            name='grado',
            unique_together={('ciclo', 'nivel', 'numero')},
        ),
    ]
