# Generated by Django 3.2.25 on 2025-04-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_auto_20250401_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoescolar',
            options={'ordering': ['meses_duracion'], 'verbose_name': 'Periodo Escolar', 'verbose_name_plural': 'Periodos Escolares'},
        ),
        migrations.AddField(
            model_name='periodoescolar',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Información adicional sobre este tipo de periodo', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='codigo',
            field=models.CharField(choices=[('SEM', 'Semestral'), ('TRI', 'Trimestral'), ('CUA', 'Cuatrimestral'), ('ANL', 'Anual')], help_text='Código de 3 letras para el tipo de periodo', max_length=3, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='meses_duracion',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='Duración en meses'),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='nombre',
            field=models.CharField(editable=False, max_length=20, verbose_name='Nombre completo'),
        ),
        migrations.AlterModelTable(
            name='periodoescolar',
            table='periodos_escolares',
        ),
    ]
