# Generated by Django 3.2.25 on 2025-04-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_auto_20250401_1704'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='periodoescolar',
            table=None,
        ),
    ]
