# Generated by Django 3.2.25 on 2025-04-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_alter_periodoescolar_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloescolar',
            name='tipo_duracion',
            field=models.CharField(choices=[('TRAD', 'Tradicional (10 meses)'), ('CUAT', 'Cuatrimestral (12 meses)'), ('TRIM', 'Trimestral (12 meses)'), ('SEM', 'Semestral (12 meses)'), ('PERS', 'Personalizado')], default='TRAD', max_length=4, verbose_name='Tipo de duración'),
        ),
    ]
