# Generated by Django 3.2.25 on 2025-04-02 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_remove_estudiante_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ciclo_inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.cicloescolar', verbose_name='Ciclo de Inscripción'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CURP inválida.', regex='^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z]{2}$')], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.grupo', verbose_name='Grupo Actual'),
        ),
    ]
