# Generated by Django 3.2.25 on 2025-04-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_auto_20250402_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveleducativo',
            name='codigo',
            field=models.CharField(choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria'), ('BAC', 'Bachillerato')], default='SEC', max_length=3, unique=True),
        ),
    ]
