# Generated by Django 3.2.25 on 2025-04-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0004_auto_20250329_0211'),
        ('estudiantes', '0011_alter_niveleducativo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='padres.padre', verbose_name='Padre/Tutor'),
        ),
    ]
