# Generated by Django 3.2.25 on 2025-04-04 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_estudiante_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='registro_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
