# Generated by Django 3.2.25 on 2025-03-28 07:15

import django.core.validators
from django.db import migrations, models
import padres.models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padre',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=padres.models.user_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen de perfil'),
        ),
    ]
