# Generated by Django 3.2.25 on 2025-03-29 03:20

from django.db import migrations, models
import padres.models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0002_alter_padre_imagen_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padre',
            options={'verbose_name': 'Padre/Madre/Tutor', 'verbose_name_plural': 'Padres/Madres/Tutores'},
        ),
        migrations.RemoveField(
            model_name='padre',
            name='rol_usuario',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='ultima_fecha_sesion',
        ),
        migrations.AddField(
            model_name='padre',
            name='google_auth_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='padre',
            name='microsoft_auth_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='padre',
            name='ultimo_acceso',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='padre',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='estado_cuenta',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente de verificación')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='padre',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=padres.models.user_image_path, verbose_name='Imagen de perfil'),
        ),
    ]
