# Generated by Django 3.2.25 on 2025-03-29 08:11

import django.core.validators
from django.db import migrations, models
import padres.models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0003_auto_20250328_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padre',
            options={},
        ),
        migrations.RemoveField(
            model_name='padre',
            name='google_auth_enabled',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='microsoft_auth_enabled',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='ultimo_acceso',
        ),
        migrations.AddField(
            model_name='padre',
            name='rol_usuario',
            field=models.CharField(default='Padre', max_length=50),
        ),
        migrations.AddField(
            model_name='padre',
            name='ultima_fecha_sesion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='padre',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='padre',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='padre',
            name='estado_cuenta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='padre',
            name='fecha_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='padre',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=padres.models.user_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen de perfil'),
        ),
    ]
