# Generated by Django 3.2.25 on 2025-05-13 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padres', '0004_auto_20250329_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padre', to=settings.AUTH_USER_MODEL),
        ),
    ]
