# Generated by Django 3.2.25 on 2025-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0008_alter_padre_personal_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padre',
            name='personal_theme',
            field=models.CharField(blank=True, choices=[('css/themes/default.css', 'Tema Default'), ('css/themes/dark.css', 'Tema Oscuro'), ('css/themes/light.css', 'Tema Claro')], max_length=100, null=True),
        ),
    ]
