# Generated by Django 3.2.25 on 2025-03-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='estado_disponibilidad',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='horario_atencion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='reglas_horario_atencion',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estado_cuenta',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='profesores/'),
        ),
    ]
