# Generated by Django 3.2.25 on 2025-03-27 05:58

from django.db import migrations, models
import profesores.models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_auto_20250326_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=profesores.models.user_image_path, verbose_name='Imagen de perfil'),
        ),
    ]
