# Generated by Django 3.2.25 on 2025-03-28 05:11

import django.core.validators
from django.db import migrations, models
import profesores.models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_alter_profesor_imagen_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=profesores.models.user_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen de perfil'),
        ),
    ]
