# Generated by Django 3.2.25 on 2025-04-03 04:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_alter_niveleducativo_codigo'),
        ('profesores', '0004_alter_profesor_imagen_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la materia')),
                ('nivel_educativo', models.CharField(choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria'), ('BAC', 'Bachillerato')], max_length=3, verbose_name='Nivel educativo')),
                ('tipo_asignatura', models.CharField(choices=[('OBL', 'Obligatoria'), ('OPT', 'Optativa'), ('EXT', 'Extracurricular')], default='OBL', max_length=3, verbose_name='Tipo de asignatura')),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='estudiantes.cicloescolar', verbose_name='Ciclo escolar')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='estudiantes.grupo', verbose_name='Grupo asignado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='profesores.profesor', verbose_name='Profesor titular')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'grupo', 'ciclo_escolar')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de término')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='estudiantes.cicloescolar', verbose_name='Ciclo escolar')),
            ],
            options={
                'verbose_name': 'Periodo Escolar',
                'verbose_name_plural': 'Periodos Escolares',
                'ordering': ['fecha_inicio'],
                'unique_together': {('ciclo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de finalización')),
                ('aula', models.CharField(max_length=20, verbose_name='Aula asignada')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='profesores.clase')),
            ],
            options={
                'verbose_name': 'Horario de clase',
                'verbose_name_plural': 'Horarios de clases',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('clase', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('faltas', models.PositiveSmallIntegerField(default=0, verbose_name='Faltas acumuladas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='profesores.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='estudiantes.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='estudiantes.periodoescolar', verbose_name='Periodo escolar')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['periodo', 'clase', 'estudiante'],
                'unique_together': {('estudiante', 'clase', 'periodo')},
            },
        ),
    ]
