# Generated by Django 3.2.25 on 2025-04-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_estudiante_registro_token'),
        ('profesores', '0005_calificacion_clase_horarioclase_periodoescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoLibreProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_libres_profesores', to='estudiantes.cicloescolar')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_libres', to='profesores.profesor')),
            ],
            options={
                'verbose_name': 'Tiempo libre del profesor',
                'verbose_name_plural': 'Tiempos libres de profesores',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('profesor', 'dia_semana', 'hora_inicio', 'ciclo_escolar')},
            },
        ),
    ]
