# Generated by Django 3.2.25 on 2025-05-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_estudiante_registro_token'),
        ('profesores', '0006_tiempolibreprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='nivel_educativo_char',
            field=models.CharField(blank=True, choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria'), ('BAC', 'Bachillerato')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nivel_educativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estudiantes.niveleducativo'),
        ),
    ]
