# Generated by Django 3.2.25 on 2025-05-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0007_auto_20250510_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='nivel_educativo_char',
        ),
    ]
