# Generated by Django 3.2.25 on 2025-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0008_remove_clase_nivel_educativo_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='google_calendar_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
