# Generated by Django 3.2.25 on 2025-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0010_profesor_personal_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='personal_theme',
            field=models.CharField(blank=True, choices=[('css/%20themes/default.css', 'Tema Default'), ('css/%20themes/dark.css', 'Tema Oscuro'), ('css/%20themes/light.css', 'Tema Claro')], max_length=100, null=True),
        ),
    ]
